In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

/Users/Rohan/Documents/Conda/anaconda3/envs/ChatbotVE/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:

creditData = pd.read_csv("/Users/Rohan/git/MLA/Datasets/credit_data.csv")

print(creditData.head())
print(creditData.describe())
print(creditData.corr())

features = creditData[["income","age","loan"]]
target = creditData.default

   clientid        income        age         loan       LTI  default
0         1  66155.925095  59.017015  8106.532131  0.122537        0
1         2  34415.153966  48.117153  6564.745018  0.190752        0
2         3  57317.170063  63.108049  8020.953296  0.139940        0
3         4  42709.534201  45.751972  6103.642260  0.142911        0
4         5  66952.688845  18.584336  8770.099235  0.130989        1
          clientid        income          age          loan          LTI  \
count  2000.000000   2000.000000  2000.000000   2000.000000  2000.000000
mean   1000.500000  45331.600018    40.927143   4444.369695     0.098403
std     577.494589  14326.327119    13.262450   3045.410024     0.057620
min       1.000000  20014.489470    18.055189      1.377630     0.000049
25%     500.750000  32796.459717    29.062492   1939.708847     0.047903
50%    1000.500000  45789.117313    41.382673   3974.719419     0.099437
75%    1500.250000  57791.281668    52.596993   6432.410625     0.147585
max    2000.000000  69995.685578    63.971796  13766.051239     0.199938

           default
count  2000.000000
mean      0.141500
std       0.348624
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000
          clientid    income       age      loan       LTI   default
clientid  1.000000  0.039280 -0.030341  0.018931  0.002538 -0.020145
income    0.039280  1.000000 -0.034984  0.441117 -0.019862  0.002284
age      -0.030341 -0.034984  1.000000  0.006561  0.021588 -0.444765
loan      0.018931  0.441117  0.006561  1.000000  0.847495  0.377160
LTI       0.002538 -0.019862  0.021588  0.847495  1.000000  0.433261
default  -0.020145  0.002284 -0.444765  0.377160  0.433261  1.000000

In [4]:
print(features)
print(target)

            income        age          loan
0     66155.925095  59.017015   8106.532131
1     34415.153966  48.117153   6564.745018
2     57317.170063  63.108049   8020.953296
3     42709.534201  45.751972   6103.642260
4     66952.688845  18.584336   8770.099235
5     24904.064140  57.471607     15.498598
6     48430.359613  26.809132   5722.581981
7     24500.141984  32.897548   2971.003310
8     40654.892537  55.496853   4755.825280
9     25075.872771  39.776378   1409.230371
10    64131.415372  25.679575   4351.028971
11    59436.847123  60.471936   9254.244538
12    61050.346079  26.355044   5893.264659
13    27267.995458  61.576776   4759.787581
14    63061.960174  39.201553   1850.369377
15    50501.726689  28.218361   3977.287432
16    43548.654711  39.574530   3935.544453
17    43378.175194  60.848318   3277.737553
18    20542.365073  61.690571   3157.442290
19    58887.357549  26.076093   4965.516066
20    23000.784002  31.761354   1148.118057
21    32197.620701  52.423280   4244.057136
22    23329.319414  48.576975    222.622299
23    27845.800894  51.970624   4959.921226
24    65301.984029  48.840922   5465.267886
25    47451.630123  27.031741   5361.282716
26    63287.038908  36.496976   9595.286289
27    45727.459870  55.839922   6376.822949
28    59417.805406  30.858267   2082.625938
29    58842.891308  54.510948  10871.186790
...            ...        ...           ...
1970  68047.925311  47.694520   4023.064765
1971  36275.735863  30.308184    644.384195
1972  52389.366848  54.969313  10398.820592
1973  23678.376111  47.466485   1779.814597
1974  37707.642948  31.344048    268.290971
1975  57753.568962  54.235915   5067.449964
1976  30529.963288  47.604402   6046.840845
1977  44022.268737  31.192627   1707.672870
1978  58533.884683  40.518963   7832.443321
1979  33702.531834  48.148404    922.036590
1980  40236.872067  52.580773   4354.314412
1981  62619.155988  43.999461   3959.611772
1982  50738.362193  45.993199   9719.562798
1983  64466.760138  33.327144   8537.369666
1984  64636.402186  60.886966   2583.106425
1985  22371.522191  39.142225   2291.856428
1986  67994.988470  38.622259   7289.014109
1987  49640.004702  20.542409   5760.858734
1988  42067.246446  24.270612   4601.606183
1989  43662.092688  25.252609   7269.596897
1990  34237.575419  34.101654   2658.090632
1991  26300.446554  45.539385   2317.393678
1992  30803.806165  23.250084    623.024153
1993  54421.410155  26.821928   3273.631823
1994  24254.700791  37.751622   2225.284643
1995  59221.044874  48.518179   1926.729397
1996  69516.127573  23.162104   3503.176156
1997  44311.449262  28.017167   5522.786693
1998  43756.056605  63.971796   1622.722598
1999  69436.579552  56.152617   7378.833599

[2000 rows x 3 columns]
0       0
1       0
2       0
3       0
4       1
5       0
6       0
7       1
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
1970    0
1971    0
1972    0
1973    0
1974    0
1975    0
1976    0
1977    0
1978    0
1979    0
1980    0
1981    0
1982    0
1983    1
1984    0
1985    0
1986    0
1987    0
1988    0
1989    1
1990    0
1991    0
1992    0
1993    0
1994    0
1995    0
1996    0
1997    1
1998    0
1999    0
Name: default, Length: 2000, dtype: int64

In [3]:

feature_train, feature_test, target_train, target_test = train_test_split(features,target, test_size=0.3)

model = LogisticRegression()
model.fit = model.fit(feature_train, target_train)
predictions = model.fit.predict(feature_test)

print(confusion_matrix(target_test, predictions))
print(accuracy_score(target_test,predictions))

[[517  14]
 [ 33  36]]
0.9216666666666666